todoapp:
  site:
    author: SpringRunner
    description: What're your plans today?
  data:
    initialize: true

spring:
  application:
    name: todos

server:
  servlet:
    encoding:
      mapping:
        en: ISO-8859-1
        ko: UTF-8
      charset: utf-8
      force: true

logging:
  level:
    '[todoapp]': debug
    '[org.springframework.beans]': debug
    web: trace
    sql: debug