todoapp:
  site:
    author: SpringRunner
    description: What're your plans today?
  data:
    initialize: true

spring:
  application:
    name: todos

logging:
  level:
    '[todoapp]': debug
    '[org.springframework.beans]': debug
    web: trace
    sql: debug