todoapp:
  site:
    author: SpringRunner
    description: What're your plans today?
  feature-toggles:
    auth: true
    online-users-counter: true
  data:
    initialize: true

spring:
  application:
    name: todos

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      mapping:
        en: ISO-8859-1
        ko: UTF-8
      charset: utf-8
      force: true

logging:
  level:
    '[todoapp]': debug
    '[org.springframework.beans]': debug
    web: trace
    sql: debug