todoapp:
  site:
    author: SpringRunner
    description: What're your plans today?

spring:
  application:
    name: todos

logging:
  level:
    '[org.springframework.beans]': debug
    web: trace
    sql: debug