todoapp:
  site:
    author: SpringRunner
    description: What're your plans today?
  data:
    initialize: true
  feature-toggles:
    auth: true
    online-users-counter: false

spring:
  application:
    name: todo

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: utf-8
      force: true

logging:
  level:
    '[todoapp]': debug
    web: trace
    sql: debug
