todoapp:
  feature-toggles:
    auth: true
    online-users-counter: false
  site:
    author: SpringRunner
    description: What're your plans today?
  data:
    initialize: true

spring:
  application:
    name: todos

server:
  servlet:
    encoding:
      charset: utf-8
      force: true

logging:
  level:
    web: debug
    '[todoapp]': debug